#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'Please provide the block device name that you intend to be used by MapR container, e.g. /dev/xvdf'
    echo 'You can find available block devices by using "lsblk" command on a Linux system.'
    exit 0
fi

blk_dev=$1

bdev=${blk_dev#/dev/}

ifdev=`lsblk | grep $bdev`

if [ -z "$ifdev" ]; then
    echo "Can't find provided block device name on this host: $dev"
    echo 'You can find available block devices by using "lsblk" command on a Linux system.'
    exit
fi

docker run -d -e HOST_BLOCK_DEVICE=$blk_dev --device=$blk_dev --privileged=true -p 22222:22 -p 31010:31010 -p 8047:8047 -p 8443:8443 -p 19888:19888 -p 8088:8088 jameshtsun/mapr5.2:light

